#!/usr/bin/env python

import os, sys, subprocess

args = sys.argv[1:]
env = dict(os.environ)
env['PYTHONPATH'] = '.:../../schemaish:../../validatish:../../convertish:../../formish:../../dottedish'
subprocess.call(args, env=env)

